### ISSUE TITLE
DAS query output format

### ISSUE THREAD

**Issue by CICS-Oleg** [singnet/das-query-engine#121]
I have a question regarding current `query` method output format. Is it true that a dict returned by the `query` method has no references to the input query? I. e. is there any binding between input query variables and returned patterns? Some analog of a field `'mapping'` in the previous output format. I have to parse and store separate list of the query variables with no guarantee that this list is correctly matched with the output list of retrieved patterns at the moment.

**Comment by andre-senna** [comment]
@CICS-Oleg  @marcocapozzoli 

Yes we still have such mapping but it's not visible. This is something we are working in this iteration but anyway we can make a quick change to make it visible. This is the current implementation of DAS.query():

```
    def query(
        self,
        query: Dict[str, Any],
        parameters: Optional[Dict[str, Any]] = {},
    ) -> List[Dict[str, Any]]:

        query_results = self._recursive_query(query, parameters)
        answer = []
        for result in query_results:
            answer.append(result.subgraph)
        return answer
```

`_recursive_query()` doesn´t return a list, it actually returns an iterator which is used to build a list of subgraphs which is what you get as response right now. `query()` is supposed to return this iterator rather than actually iterating through it to build such list. This is an iterator on objects of the type QueryAnswer:

```
class QueryAnswer:
    subgraph: Optional[Dict] = None
    assignment: Optional[Assignment] = None
```

So each QueryAnswer carries the subgraph and the variable mapping that is related to that subgraph (the object `Assignment` have a field `mapping` which is a Dict mapping from variable names to handles).

My propose is to change `DAS.query()` to return this iterator instead of the list it currently does. This change would need to be done anyway in the near future together with other changes but I want to merge a quick fix for this in advance. @CICS-Oleg  are you OK with this?

**Comment by CICS-Oleg** [comment]
@andre-senna Ok, let's try this one. Is this `QueryAnswer` class template more or less fixed? Can it be changed in the near future?

**Comment by andre-senna** [comment]
@CICS-Oleg  Yes it's supposed to be stable.
